var SUPPORTED_TYPES = {
  JSON_SCHEMA: T_JSON_SCHEMA,
  JSON: T_JSON,
  PROTO3: T_PROTO3,
  JAVA: T_JAVA,
  POSTGRES: T_POSTGRES,
  TABLE_MD: T_TABLE_MD,
  MYSQL: T_MYSQL,
};
// default: JSON_SCHEMA
var DEPEND_TYPES = {
  POSTGRES: 'TABLE_JSON',
  MYSQL: 'TABLE_JSON',
};